version: '3.5'
networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql:8.0.1
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest_db_dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    networks:
      - app-tier  
    expose:
      - 3306 
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskee-backend
    expose:
      - 4000  
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./src:/backend/src      
    networks:
      - app-tier  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    networks:
      - app-tier  
  frontend:
    env_file: .env.front.docker
    image: bmspd/taskee-frontend:latest  
    build:
      context: ./
    networks:
      - app-tier  
    ports:
     - 3030:3030  
volumes:
  dbdata:  